import type { ControlFlowGraphDto } from './types'

export const scholarshipGraph: ControlFlowGraphDto = {
  entryNodeId: 1,
  exitNodeId: 13,
  nodes: [
    { id: 1, kind: 'Entry', label: 'Inicio' },
    { id: 2, kind: 'Statement', label: 'Leer edad', sourceLine: 5 },
    { id: 3, kind: 'Statement', label: 'Leer promedio', sourceLine: 6 },
    { id: 4, kind: 'Decision', label: 'edad > 18', sourceLine: 8 },
    { id: 5, kind: 'Decision', label: 'promedio >= 9', sourceLine: 9 },
    { id: 6, kind: 'Statement', label: 'beca <- 2000', sourceLine: 10 },
    { id: 7, kind: 'Decision', label: 'promedio >= 7.5', sourceLine: 11 },
    { id: 8, kind: 'Statement', label: 'beca <- 1000', sourceLine: 12 },
    { id: 9, kind: 'Statement', label: 'beca <- 500', sourceLine: 14 },
    { id: 10, kind: 'Statement', label: 'beca <- 3000', sourceLine: 17 },
    { id: 11, kind: 'Merge', label: 'Merge' },
    { id: 12, kind: 'Statement', label: 'Escribir beca', sourceLine: 20 },
    { id: 13, kind: 'Exit', label: 'Fin' },
  ],
  edges: [
    { sourceId: 1, targetId: 2, kind: 'Normal' },
    { sourceId: 2, targetId: 3, kind: 'Normal' },
    { sourceId: 3, targetId: 4, kind: 'Normal' },
    { sourceId: 4, targetId: 5, kind: 'True', label: 'Sí' },
    { sourceId: 4, targetId: 10, kind: 'False', label: 'No' },
    { sourceId: 5, targetId: 6, kind: 'True', label: 'Sí' },
    { sourceId: 5, targetId: 7, kind: 'False', label: 'No' },
    { sourceId: 6, targetId: 11, kind: 'Normal' },
    { sourceId: 7, targetId: 8, kind: 'True', label: 'Sí' },
    { sourceId: 7, targetId: 9, kind: 'False', label: 'No' },
    { sourceId: 8, targetId: 11, kind: 'Normal' },
    { sourceId: 9, targetId: 11, kind: 'Normal' },
    { sourceId: 10, targetId: 11, kind: 'Normal' },
    { sourceId: 11, targetId: 12, kind: 'Normal' },
    { sourceId: 12, targetId: 13, kind: 'Normal' },
  ],
}
